language: node_js

node_js:
  - node

cache: yarn

script:
  - yarn ci

deploy:
  provider: npm
  email: accounts@francoisbest.com
  api_key:
    secure: LL3yHVJYeogh7PIDEbYraTOpY1WjaCW+7R3TQUOZA8LeySWtWRYcOdqVKZCe6OAbXO3gnOSF4KAWHlrOU8K366NR9PF20Wkv+vITSFiMwJtFnrNd3VoE/Bm+1XsyzSVlzCjwN/T6KWG6kUVNPm5QzDkYgR5GZZmTjs+4xw8ElIgtW0CrmmJSvUhGgAok8T/lb3/Bd1hqGoqmieuulFwANvMvIHC+S/c7P9gbM9PbVplm8gQWwIndD7sbDC2vg74Px9/WxuvoghECpQpQYAc/wIwwUKGA9ZiFAcJV67F8Ci+5xYp+OlTqpUTeD40rVTKoDxlLmFiby6ePesd7tD0qubZFmHV/IEgY9pLKOSpOgH7sqJtf9wWdvu5nDFTPBzYr0pCIYmQFNmcjwxz28TFqAdw/LCmbjPLKCSe32ZjL+t889JhCdYQuhTE72DQrbuXwjanLYh0rIXgmwzkp7c7v2O0LvienHxBO+WMLF0nK/C9VYFD7QE2+5K3FI4yAg9FJNlPLkfW8WtPwr/zAnyl2FBgX20Y3ERLhoiG8CHzKbCphzI2LZvQWJHdUwiKlCUI9btRmT8YozMnkLE5y25Jf0O+EuSQT9PEXM5ph8ZimPnnDUtNJAinKa69Aktqow2oPozjGP86kycdmYIv6VBu088e6dEo88mksaJUY5Uv8yac=
  on:
    tags: true
  skip_cleanup: true

 notifications:
  slack:
    rooms:
      secure: fdCE6KX084wf63gcaeHCfkSPhfNqlb0xCRiJFHfd3Dyh7vgkhFYR8sF8BAR1+vi3jj2FCpwvATGiNxE2Xe5QCgUFgTs22qN9mERafRl6Lt7GPdPMr3aD1YLBsD8w35BGJG3cY7F35UKJxsB6p/DoCHAr0iwizSI2/4ZbfTqhr4XuZg1qV+Wy09ChFeAMzjgAx9UKuNrCXin8aLQh2ak048xzFjzzYg8kGTVFUXDngxVTgLbmhvVAQdNsbRS2q4c0905+7MchtnW7nQyOhHuVgL+3d65RTL3wyMvI9SZZNBwUqaxAbJrX/dwMi3TOQbzc81/3dymbHM7TBzaPHrj9so2PHpmfSYUTpM+1/0wEElj9kz0eWjF2vjBZ54S+VDRehCeUoecJMVS/nveNYr3nK5+CkP9c4W9/ukyW6YtvkawXScK42tcnCFSaskrG/m7w9mmNzWQ3DcsOELOT7RozJGqSoQd/6rAl3k0qhwzaViLNDJotklO4vJ5unrBr8w/QIL+qrjWZnOm/k3YaRT+HLIotU2ch+SmyhvNDk5lSrExOvPBgg+PY7xFibxlbbjuu16NXtiHjvO/mUEQxmU7wH6744ez75k7TaX3isan8O2QQSfqceUp8BvA7w2ywlle9s+mgCHWL37UKenu3lM9XUBn03ZdszhWvPGCnGI/QS8o=
    on_success: always
    on_failure: always
    on_error: always
    template:
      - 'Build %{result}: %{repository_slug}'
      - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) on %{branch} by %{author} %{result} in %{duration}'
